# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: How It Works
    url: /#how-it-works
    weight: 20
  - name: Events
    url: /#events
    weight: 30
  - name: Community
    url: /#community
    weight: 40
  - name: Blog
    url: blog/
    weight: 50
