name = "meatup-club"
main = "./build/server/index.js"
compatibility_date = "2025-12-24"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./build/client"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "meatup-club-db"
database_id = "3a6fb3b4-0322-4ab0-b8df-09b5d19af1c1"

[vars]
NODE_VERSION = "20"
